FROM ubuntu:latest
RUN apt-get update && apt-get install -y openssh-server iproute2 iputils-ping proxychains4 vim nano
RUN mkdir /var/run/sshd
RUN useradd -m -s /bin/bash sam
RUN echo "sam:iam" | chpasswd
COPY pivot-*.conf /home/sam/
RUN chown sam: /home/sam/pivot-*.conf
RUN chmod 666 /etc/proxychains4.conf
EXPOSE 22
# Start SSH server
CMD ["/usr/sbin/sshd", "-D"]
